### ISSUE TITLE
Is this build optimized?

### ISSUE THREAD

**Issue by marbub** [flathub/org.freedesktop.Sdk.Extension.llvm18#6]
CXXFLAGS is set to "-g0". I am not sure if an "-O2" is added later. I ask because I copied it to the qt creator build, and the clangd indexer feels slower. Copying may not be the best way, but I found no way to download the extension by default.

**Comment by marbub** [comment]
Have you thought to make a PGO build? We made some benchmarks long ago, and it lead to 10-20% performance wins for LLVM.

**Comment by Erick555** [comment]
`-O2` is the default build option set by flatpak-builder and inherited from flatpak runtime
`-g0` disables debug symbols (the default is `-g`). I don't think setting one affects the other.

LTO was [enabled](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/commit/c0190340c0fc763c75f57457852e9a394f2a95ff) for a while but increased build times (abour 2-3 times for aarch64) and increased size of extenson were annoying for me while I wasn't sure what actual gains are. 

Setting PGO may be complicated however I'm open for any contributions regarding extension optimizations.

**Comment by marbub** [comment]
I understand with the build options. But I could find nothing in the documentation about appending the CXXFLAGS. Then later, they are set to "". I am not unsure if that sets them to empty or unsets them.I am not familiar with flatpak.

In a normal setup I would expect them to not have -O2. So I asked if you tested if cmakes is executing the compiler with -O2 in the second stage.

I would expect that a normal release built has no debug sections, only RelWithDebugInfo. But maybe flatpak is doing some magic here too.

**Comment by marbub** [comment]
I read https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html and cmake is doing a combination.

**Comment by Erick555** [comment]
By default flatpak-builder sets `CXXFLAGS` env variable with content available in `/etc/flatpak-builder/defaults.json` (available in `org.freedesktop.Sdk` runtime).

The current flags are:

```
{
  "libdir": "/usr/lib/x86_64-linux-gnu",
  "cflags": "-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ",
  "cxxflags": "-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ",
  "cppflags": "",
  "ldflags": "-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed "
}
```

They origin  from [there](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/include/flags.yml).

Now cmake as you noted uses `CXXFLAGS` env variable if it exist. The next step is [cxxflags](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/blob/branch/23.08/org.freedesktop.Sdk.Extension.llvm18.json#L12) in build-options from flatpak manifest - by default its content is appended to the `CXXFLAGS` env variable   - there is `cxxflags-override` option which when set to `true` replaces them instead of appending, see https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html

The last thing are cmake default build flags which rely on `-DCMAKE_BUILD_TYPE` setting and are appended to the `CXXFLAGS` during build. For RelWithDebInfo they are `-O2 -g -DNDEBUG` but since the first two are already covered  in `CXXFLAGS` then they are being [reset](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/blob/branch/23.08/org.freedesktop.Sdk.Extension.llvm18.json#L111) to just -`DNDEBUG`.

so the final build flag set when invoking cmake is: `CXXFLAGS -g0 ... -DNDEBUG`. Unfortunately [cmake-ninja](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/blob/branch/23.08/org.freedesktop.Sdk.Extension.llvm18.json#L81) generator is eating the detailed build content from the [logs](https://buildbot.flathub.org/api/v2/logs/5016999/raw) (one could use plain `cmake` generator to overcome that but it's supposedly slower. I can run a test build for you to confirm that

**Comment by marbub** [comment]
I understand CMake is not using CXXFLAGS for overriding but for appending. But I am not an expert. I only got the impression that the clangd indexing in the flakpak is slower, but that can have other causes.

**Comment by Erick555** [comment]
I don't deny llvm flatpak is slower than it should just not because it lacks `-O2`. Maybe it needs `-O3`, maybe LTO or PGO or all of them. Feel free to tinker with extension manifest adding various buildflags and open test PRs here - then you can install test extension and use it with your app to check if something improves. If it make difference I'll merge them.

**Comment by marbub** [comment]
PGO would bring a big performance boost. But that is not so easy. If I have time, I will look into it.
https://www.llvm.org/docs/HowToBuildWithPGO.html

**Comment by marbub** [comment]
@Erick555 I think I have to use the simple build system to implement the two-stage build in the same build directory. Do you have any better ideas?

**Comment by Erick555** [comment]
yes, for custom build commands simple build system may be necessary. I would even recommend putting all the build commands in `build.sh` script then make the build system to execute that script.
